version: '3'
services: 
  db:
    container_name: giru-db
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - giru:/var/lib/mysql

volumes:
  giru:
